language: php
php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - wget -O phing.phar http://www.phing.info/get/phing-2.16.0.phar
  - chmod +x phing.phar

script:
  - ./phing.phar lint
  - ./phing.phar test
